spec:
  template:
    spec:
      containers:   
      - name: configmap   
        env:
        - name: GREETING_MESSAGE       
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: greeting.message
              optional: true
       